# analysis configuration
output_dir: 'output'
targets:
  - assembly
  - small_variants
  - structural_variants

# reference-based resources
reference: 'resources/human_GRCh38_no_alt_analysis_set.fasta'
reference_index: 'resources/human_GRCh38_no_alt_analysis_set.fasta.fai'
chromosome_lengths: 'resources/human_GRCh38_no_alt_analysis_set.chr_lengths.txt'
tandem_repeats_bed: 'resources/human_GRCh38_no_alt_analysis_set.trf.bed'
stratifications: 'resources/stratifications/v2.0-GRCh38-stratifications.tsv'
sdf: 'resources/human_GRCh38_no_alt_analysis_set.sdf'
chroms: ['chr1', 'chr2', 'chr3', 'chr4', 'chr5',
              'chr6', 'chr7', 'chr8', 'chr9', 'chr10',
              'chr11', 'chr12', 'chr13', 'chr14', 'chr15',
              'chr16', 'chr17', 'chr18', 'chr19', 'chr20',
              'chr21', 'chr22', 'chrX', 'chrY', 'chrM']
              
# software configuration
deepvariant_version: '1.3.0-gpu'
n_shards: 256
